return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "cpp",
      "css",
      "diff",
      "dockerfile",
      "gitcommit",
      "gitignore",
      "go",
      "html",
      "javascript",
      "json",
      "lua",
      "markdown",
      "python",
      "query",
      "regex",
      "rust",
      "sql",
      "toml",
      "typescript",
      "vim",
      "yaml",
    },
    auto_install = true,
    highlight = { enable = true },
  },
}
